name = 'billowing-violet-4e69'
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "billowing-violet-4e69-prod"

[assets]
directory = "./frontend/public"
binding = "ASSETS"
